2021-04-29 18:24:12,561 DEBUG asyncio Using selector: EpollSelector
2021-04-29 18:24:17,577 DEBUG quic [0000000000000002] Network path ('127.0.0.1', 4987) discovered
2021-04-29 18:24:17,580 DEBUG quic [0000000000000002] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-04-29 18:24:17,594 DEBUG quic [0000000000000002] TLS State.SERVER_EXPECT_CLIENT_HELLO -> State.SERVER_EXPECT_FINISHED
2021-04-29 18:24:18,096 DEBUG quic [0000000000000002] Loss detection triggered
2021-04-29 18:24:18,146 DEBUG quic [0000000000000002] Discarding epoch Epoch.INITIAL
2021-04-29 18:24:18,148 DEBUG quic [0000000000000002] TLS State.SERVER_EXPECT_FINISHED -> State.SERVER_POST_HANDSHAKE
2021-04-29 18:24:18,148 DEBUG quic [0000000000000002] Discarding epoch Epoch.HANDSHAKE
2021-04-29 18:24:18,148 INFO quic [0000000000000002] ALPN negotiated protocol hq-29
2021-04-29 18:24:18,148 INFO quic [0000000000000002] Connection close code 0x5534, reason 
2021-04-29 18:24:18,149 DEBUG quic [0000000000000002] QuicConnectionState.CONNECTED -> QuicConnectionState.DRAINING
2021-04-29 18:24:18,149 INFO quic [0000000000000002] Connection close code 0xE697, reason 
2021-04-29 18:24:18,149 DEBUG quic [0000000000000002] QuicConnectionState.DRAINING -> QuicConnectionState.DRAINING
2021-04-29 18:24:18,149 INFO quic [0000000000000002] Connection close code 0x1C14, reason N
2021-04-29 18:24:18,149 DEBUG quic [0000000000000002] QuicConnectionState.DRAINING -> QuicConnectionState.DRAINING
2021-04-29 18:24:19,648 DEBUG quic [0000000000000002] Discarding epoch Epoch.ONE_RTT
2021-04-29 18:24:19,648 DEBUG quic [0000000000000002] QuicConnectionState.DRAINING -> QuicConnectionState.TERMINATED
2021-04-29 18:24:20,103 DEBUG quic [0e9fd30091d4ce97] Network path ('127.0.0.1', 4987) discovered
2021-04-29 18:24:20,104 DEBUG quic [0e9fd30091d4ce97] Payload decryption failed
2021-04-29 18:24:20,320 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
2021-04-29 18:24:22,012 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
2021-04-29 18:24:22,867 DEBUG quic [0000000000000002] Network path ('127.0.0.1', 4987) discovered
2021-04-29 18:24:22,869 DEBUG quic [0000000000000002] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-04-29 18:24:22,869 INFO quic [0000000000000002] Connection close code 0x2328, reason 
2021-04-29 18:24:22,869 DEBUG quic [0000000000000002] QuicConnectionState.CONNECTED -> QuicConnectionState.DRAINING
2021-04-29 18:24:23,064 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
