2021-06-02 11:41:24,062 DEBUG asyncio Using selector: EpollSelector
2021-06-02 11:41:24,067 DEBUG quic [3ded1e6aa3dc4aff] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2021-06-02 11:41:24,452 DEBUG quic [3ded1e6aa3dc4aff] Decryption key is not available
2021-06-02 11:41:24,570 DEBUG quic [3ded1e6aa3dc4aff] Loss detection triggered
2021-06-02 11:41:24,820 DEBUG quic [3ded1e6aa3dc4aff] Decryption key is not available
2021-06-02 11:41:25,358 DEBUG quic [3ded1e6aa3dc4aff] Decryption key is not available
2021-06-02 11:41:25,573 DEBUG quic [3ded1e6aa3dc4aff] Loss detection triggered
2021-06-02 11:41:26,389 DEBUG quic [3ded1e6aa3dc4aff] Decryption key is not available
2021-06-02 11:41:26,586 DEBUG quic [3ded1e6aa3dc4aff] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-06-02 11:41:26,587 DEBUG quic [3ded1e6aa3dc4aff] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2021-06-02 11:41:26,901 WARNING quic [3ded1e6aa3dc4aff] Error: 10, reason: Unexpected frame type, frame_type: 30
2021-06-02 11:41:26,901 DEBUG quic [3ded1e6aa3dc4aff] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
2021-06-02 11:41:28,402 DEBUG quic [3ded1e6aa3dc4aff] Discarding epoch Epoch.INITIAL
2021-06-02 11:41:28,403 DEBUG quic [3ded1e6aa3dc4aff] Discarding epoch Epoch.HANDSHAKE
2021-06-02 11:41:28,403 DEBUG quic [3ded1e6aa3dc4aff] Discarding epoch Epoch.ONE_RTT
2021-06-02 11:41:28,403 DEBUG quic [3ded1e6aa3dc4aff] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
Traceback (most recent call last):
  File "examples/http3_client.py", line 465, in <module>
    zero_rtt=args.zero_rtt,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 313, in run
    wait_connected=not zero_rtt,
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/compat.py", line 17, in __aenter__
    return await self.gen.__anext__()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/client.py", line 89, in connect
    await protocol.wait_connected()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError
