2021-03-28 03:04:55,022 DEBUG asyncio Using selector: EpollSelector
2021-03-28 03:04:59,859 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4987) discovered
2021-03-28 03:04:59,861 DEBUG quic [0000000000000001] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-03-28 03:04:59,873 DEBUG quic [0000000000000001] TLS State.SERVER_EXPECT_CLIENT_HELLO -> State.SERVER_EXPECT_FINISHED
2021-03-28 03:05:00,082 DEBUG quic [0000000000000001] Discarding epoch Epoch.INITIAL
2021-03-28 03:05:00,083 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4987) validated by handshake
2021-03-28 03:05:00,377 DEBUG quic [0000000000000001] TLS State.SERVER_EXPECT_FINISHED -> State.SERVER_POST_HANDSHAKE
2021-03-28 03:05:00,377 DEBUG quic [0000000000000001] Discarding epoch Epoch.HANDSHAKE
2021-03-28 03:05:00,377 INFO quic [0000000000000001] ALPN negotiated protocol hq-29
2021-03-28 03:05:00,574 DEBUG quic [3349d0008924d358] Network path ('127.0.0.1', 4987) discovered
2021-03-28 03:05:00,575 DEBUG quic [3349d0008924d358] Payload decryption failed
2021-03-28 03:05:00,907 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
2021-03-28 03:05:01,027 DEBUG quic [0000000000000001] Loss detection triggered
2021-03-28 03:05:01,028 DEBUG quic [0000000000000001] Sending PING (probe) in packet 4
2021-03-28 03:05:01,291 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4988) discovered
2021-03-28 03:05:01,291 DEBUG quic [0000000000000001] Stream 4 created by peer
2021-03-28 03:05:01,292 DEBUG quic [0000000000000001] Received PING (probe) response
2021-03-28 03:05:01,292 DEBUG quic [0000000000000001] Peer switching to CID 3349d0008924d358 (1)
2021-03-28 03:05:01,292 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4988) promoted
2021-03-28 03:05:01,293 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:05:01,711 DEBUG quic [0000000000000001] Stream 12 created by peer
2021-03-28 03:05:01,712 DEBUG quic [0000000000000001] Stream 20 created by peer
2021-03-28 03:05:01,712 DEBUG quic [0000000000000001] Stream 16 created by peer
2021-03-28 03:05:01,712 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4987) promoted
2021-03-28 03:05:01,712 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:05:01,713 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:05:01,713 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:05:01,942 WARNING quic [0000000000000001] Error: 10, reason: Response does not match challenge, frame_type: 27
2021-03-28 03:05:01,942 DEBUG quic [0000000000000001] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
