2021-05-30 11:05:11,090 DEBUG asyncio Using selector: EpollSelector
2021-05-30 11:05:11,097 DEBUG quic [240469d63a6afe8b] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2021-05-30 11:05:11,395 DEBUG quic [240469d63a6afe8b] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-05-30 11:05:11,396 DEBUG quic [240469d63a6afe8b] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2021-05-30 11:05:11,571 DEBUG quic [240469d63a6afe8b] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2021-05-30 11:05:11,571 DEBUG quic [240469d63a6afe8b] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2021-05-30 11:05:11,572 DEBUG quic [240469d63a6afe8b] TLS State.CLIENT_EXPECT_CERTIFICATE_VERIFY -> State.CLIENT_EXPECT_FINISHED
2021-05-30 11:05:11,573 DEBUG quic [240469d63a6afe8b] TLS State.CLIENT_EXPECT_FINISHED -> State.CLIENT_POST_HANDSHAKE
2021-05-30 11:05:11,573 WARNING quic [240469d63a6afe8b] Error: 8, reason: original_destination_connection_id does not match, frame_type: QuicFrameType.CRYPTO
2021-05-30 11:05:11,573 DEBUG quic [240469d63a6afe8b] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
2021-05-30 11:05:13,075 DEBUG quic [240469d63a6afe8b] Discarding epoch Epoch.INITIAL
2021-05-30 11:05:13,075 DEBUG quic [240469d63a6afe8b] Discarding epoch Epoch.HANDSHAKE
2021-05-30 11:05:13,075 DEBUG quic [240469d63a6afe8b] Discarding epoch Epoch.ONE_RTT
2021-05-30 11:05:13,075 DEBUG quic [240469d63a6afe8b] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
Traceback (most recent call last):
  File "examples/http3_client.py", line 465, in <module>
    zero_rtt=args.zero_rtt,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 313, in run
    wait_connected=not zero_rtt,
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/compat.py", line 17, in __aenter__
    return await self.gen.__anext__()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/client.py", line 89, in connect
    await protocol.wait_connected()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError
