2021-06-02 11:35:39,374 DEBUG asyncio Using selector: EpollSelector
2021-06-02 11:35:39,379 DEBUG quic [e6313d19602e011c] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2021-06-02 11:35:39,840 DEBUG quic [e6313d19602e011c] Decryption key is not available
2021-06-02 11:35:39,881 DEBUG quic [e6313d19602e011c] Loss detection triggered
2021-06-02 11:35:40,321 DEBUG quic [e6313d19602e011c] Decryption key is not available
2021-06-02 11:35:40,445 DEBUG quic [e6313d19602e011c] Decryption key is not available
2021-06-02 11:35:40,871 DEBUG quic [e6313d19602e011c] Decryption key is not available
2021-06-02 11:35:40,883 DEBUG quic [e6313d19602e011c] Loss detection triggered
2021-06-02 11:35:41,079 DEBUG quic [e6313d19602e011c] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-06-02 11:35:41,080 DEBUG quic [e6313d19602e011c] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2021-06-02 11:35:41,471 WARNING quic [e6313d19602e011c] Error: 10, reason: Unexpected frame type, frame_type: 30
2021-06-02 11:35:41,471 DEBUG quic [e6313d19602e011c] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
2021-06-02 11:35:42,972 DEBUG quic [e6313d19602e011c] Discarding epoch Epoch.INITIAL
2021-06-02 11:35:42,972 DEBUG quic [e6313d19602e011c] Discarding epoch Epoch.HANDSHAKE
2021-06-02 11:35:42,972 DEBUG quic [e6313d19602e011c] Discarding epoch Epoch.ONE_RTT
2021-06-02 11:35:42,972 DEBUG quic [e6313d19602e011c] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
Traceback (most recent call last):
  File "examples/http3_client.py", line 465, in <module>
    zero_rtt=args.zero_rtt,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 313, in run
    wait_connected=not zero_rtt,
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/compat.py", line 17, in __aenter__
    return await self.gen.__anext__()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/client.py", line 89, in connect
    await protocol.wait_connected()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError
