between random: 111154803
between random: 111154795
between random: 111154803
between random: 61683
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
timeout: the monitored command dumped core
Aborted
output directory: temp/7510
implementation directory: /quic/aioquic
implementation command: python3 examples/http3_server.py --certificate /quic/aioquic/tests/ssl_cert.pem --private-key /quic/aioquic/tests/ssl_key.pem  -v --host 127.0.0.1 --port 4443 -l /results/temp/aioquic_key.log"
../quic_server_test_retirecoid_error (0) ...
implementation command: ['python3', 'examples/http3_server.py', '--certificate', '/quic/aioquic/tests/ssl_cert.pem', '--private-key', '/quic/aioquic/tests/ssl_key.pem', '-v', '--host', '127.0.0.1', '--port', '4443', '-l', '/results/temp/aioquic_key.log"']
quic_process pid: 7606
timeout 100 ./build/quic_server_test_retirecoid_error seed=685 the_cid=0 server_cid=1 client_port=4987 client_port_alt=4988
client return code: 134
FAIL
error: 1 tests(s) failed
